### ISSUE TITLE
pymarkdown project

### ISSUE THREAD

**Issue by nehalecky** [JanSchulz/knitpy#30]
Hello! 

As I have been investigating tools in this area, just wanted to point out the [pymarkdown](https://github.com/mrocklin/pymarkdown) project by @mrocklin as it seems like they both have the same end goal? Apologies in advance if I am overlooking an existing discussion that already covered this or if I am overgeneralizing the goals of each project.

So awesome to see this effort, hope to contribute soon. :)

**Comment by mrocklin** [comment]
You should use and contribute to knitpy, not pymarkdown.  Pymarkdown was a
single weekend toy project, is far less mature, and is not maintained.

**Comment by nehalecky** [comment]
Thanks @mrocklin for reply, appreciated. Should we consider any particular functionality from pymarkdown that you think beneficial for this project?

**Comment by mrocklin** [comment]
Not really.  It was a pretty ugly hack.

**Comment by nehalecky** [comment]
Refreshing straightforwardness—thanks. For a weekend project, nice work. I also appreciate the documentation. 

So, it seems like the community will be making camp here at [knitpy](https://github.com/JanSchulz/knitpy/) for the time being. :)

What will you do with pymarkdown? Perhaps we should try and redirect interest to this project? (brief history: I came across pymarkdown first and had cloned it to begin exploring).

**Comment by mrocklin** [comment]
See https://github.com/mrocklin/pymarkdown/commit/22ad745e3dd55c5f3b968d310376833020657668

**Comment by nehalecky** [comment]
@mrocklin: Thanks, this was perhaps my fastest issue resolution. Closing.
